package ru.serov.springchat.WebChat.models;

import jakarta.persistence.*;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.NotEmpty;

import java.io.Serializable;
import java.security.Timestamp;

@Entity
@Table(name = "messages")
public class Messages implements Serializable {

    //    CREATE TABLE messages(
//            message_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Порядковый id сообщений --);
//    chat_id INT NOT NULL, -- id чата --
//    user_id INT NOT NULL, -- id пользователя, который добавил сообщение --,
//    context VARCHAR(200) NOT NULL, -- Текст сообщения --
//    date_create TIMESTAMP NOT NULL, -- Дата сообщения --
//    PRIMARY KEY (message_id),
//    FOREIGN KEY (chat_id) REFERENCES chat(chat_id),
//    FOREIGN KEY (user_id) REFERENCES users(user_id)
//            );

    @Id
    @Column(name = "messages_id")
    @NotEmpty
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int message_id;

    @ManyToOne
    @JoinColumn(name = "chat_id")
    @NotEmpty
    private Chat chat;

    @ManyToOne
    @JoinColumn(name = "user_id")
    @NotEmpty
    private User user;

    @Column(name = "context")
    @NotEmpty
    @Max(value = 200, message = "Message must less then 200 character")
    private String context;

    @Column(name = "data_create")
    private Timestamp data_create;

    public Messages() {
    }

    public Messages( Chat chat, User user, String context, Timestamp data_create) {
        this.chat = chat;
        this.user = user;
        this.context = context;
        this.data_create = data_create;
    }

    public int getMessage_id() {
        return message_id;
    }

    public void setMessage_id(int message_id) {
        this.message_id = message_id;
    }

    public Chat getChat() {
        return chat;
    }

    public void setChat(Chat chat) {
        this.chat = chat;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getContext() {
        return context;
    }

    public void setContext(String context) {
        this.context = context;
    }

    public Timestamp getData_create() {
        return data_create;
    }

    public void setData_create(Timestamp data_create) {
        this.data_create = data_create;
    }
}
